# Generated by Django 5.2.7 on 2025-10-10 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('descriptio', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='add_date')),
                ('requirid_date', models.DateTimeField(auto_now_add=True, verbose_name='add_date')),
                ('shipped_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('unit_price', models.CharField(max_length=100)),
                ('discontinued', models.CharField(max_length=100)),
                ('category_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app111.categories')),
            ],
        ),
        migrations.CreateModel(
            name='order_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('order_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app111.orders')),
                ('product_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app111.products')),
            ],
        ),
    ]
