# Generated by Django 5.2.7 on 2025-10-14 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_categories_orders_remove_news_category_products_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='descriptio',
            new_name='description',
        ),
    ]
