# Generated by Django 5.2.7 on 2025-10-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_descriptio_categories_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='requirid_date',
        ),
        migrations.AddField(
            model_name='orders',
            name='required_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='shipped_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
